coverage:
  status:
    project:
      default:
        enabled: true
        # Allow up to 5% drop in overall project coverage before failing
        threshold: 5%
    patch:
      default:
        enabled: false