site_name: Auris Tools
site_description: The swiss knife tools to coordinate cloud frameworks with an easy approach for Auris platforms
site_author: Antonio Senra
repo_url: https://github.com/AurisAASI/auris-tools
repo_name: AurisAASI/auris-tools

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - toc:
      permalink: true

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [auris_tools]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            heading_level: 3
            show_signature_annotations: true
            separate_signature: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage:
    - Getting Started: usage/getting-started.md
    - Configuration: usage/configuration.md
  - API Reference:
    - Overview: api/overview.md
    - Configuration: api/configuration.md
    - Database Handlers: api/database-handlers.md
    - Office Word Handler: api/office-word-handler.md
    - Storage Handler: api/storage-handler.md
    - Textract Handler: api/textract-handler.md
    - Gemini Handler: api/gemini-handler.md
    - Utilities: api/utils.md
  - Contributing: contributing.md